// <auto-generated />
using CEN4020_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CEN4020_Website.Migrations
{
    [DbContext(typeof(Dbctxt))]
    [Migration("20220709040221_AddReviewToDb")]
    partial class AddReviewToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CEN4020_Website.Pages.PaperReview.AddReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"), 1L, 1);

                    b.Property<int>("AppropriatenessOfTopic")
                        .HasColumnType("int");

                    b.Property<int>("CitationOfPreviousWork")
                        .HasColumnType("int");

                    b.Property<int>("ClarityOfMessage")
                        .HasColumnType("int");

                    b.Property<int>("ComfortLevelAcceptability")
                        .HasColumnType("int");

                    b.Property<int>("ComfortLevelTopic")
                        .HasColumnType("int");

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<string>("ContentComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mechanics")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationOfPaper")
                        .HasColumnType("int");

                    b.Property<int>("Originality")
                        .HasColumnType("int");

                    b.Property<int>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("OverallRatingComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaperID")
                        .HasColumnType("int");

                    b.Property<int>("PotentialForOralPresentationComments")
                        .HasColumnType("int");

                    b.Property<int>("PotentialInterestInTopic")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerID")
                        .HasColumnType("int");

                    b.Property<int>("ScopeOfCoverage")
                        .HasColumnType("int");

                    b.Property<int>("SuitabilityForPresentation")
                        .HasColumnType("int");

                    b.Property<int>("SupportiveEvidence")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalQuality")
                        .HasColumnType("int");

                    b.Property<int>("TimelinessOfTopic")
                        .HasColumnType("int");

                    b.Property<string>("WrittenDocumentsComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.ToTable("AddReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
